# Generated by Django 2.1.3 on 2019-01-26 21:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', ckeditor.fields.RichTextField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('articleUrl', models.URLField(max_length=500)),
                ('imageUrl', models.URLField(max_length=500)),
                ('date', ckeditor.fields.RichTextField(max_length=100)),
                ('article', ckeditor.fields.RichTextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='tags',
            field=models.ManyToManyField(to='News.tags'),
        ),
    ]
