# Generated by Django 2.1.3 on 2018-11-25 14:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20181125_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='articleUrl',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='date',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='imageUrl',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='source',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
