# Generated by Django 2.1.3 on 2018-11-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0003_phonereview_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonespecs',
            name='phone_image',
        ),
        migrations.AddField(
            model_name='phonereview',
            name='review_image',
            field=models.ImageField(blank=True, null=True, upload_to='phonesimages/'),
        ),
        migrations.AddField(
            model_name='phonespecs',
            name='specs_image',
            field=models.ImageField(blank=True, null=True, upload_to='phonesimages/'),
        ),
        migrations.AlterField(
            model_name='phonereview',
            name='batterylife_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phonereview',
            name='camera_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phonereview',
            name='competition_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phonereview',
            name='cons_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phonereview',
            name='description',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phonereview',
            name='design_hardware_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phonereview',
            name='display_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phonereview',
            name='introduction_releasedate_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phonereview',
            name='performance_price_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phonereview',
            name='pros_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phonereview',
            name='software_os_softwarefeatures_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
