# Generated by Django 2.1.3 on 2018-11-26 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0006_auto_20181125_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewcomment',
            old_name='content',
            new_name='review_content',
        ),
        migrations.RenameField(
            model_name='reviewcomment',
            old_name='post',
            new_name='review_post',
        ),
        migrations.RenameField(
            model_name='reviewcomment',
            old_name='user',
            new_name='review_user',
        ),
        migrations.RenameField(
            model_name='specscomment',
            old_name='content',
            new_name='specs_comment',
        ),
        migrations.RenameField(
            model_name='specscomment',
            old_name='post',
            new_name='specs_post',
        ),
        migrations.RenameField(
            model_name='specscomment',
            old_name='user',
            new_name='specs_user',
        ),
        migrations.RemoveField(
            model_name='reviewcomment',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='specscomment',
            name='reply',
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='review_reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewreplies', to='Devices.ReviewComment'),
        ),
        migrations.AddField(
            model_name='specscomment',
            name='specs_reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specsreplies', to='Devices.SpecsComment'),
        ),
    ]
