# Generated by Django 2.1.3 on 2019-01-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0007_auto_20181126_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonespecs',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
