# Generated by Django 2.1.3 on 2019-01-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Devices', '0008_phonespecs_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonereview',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='phonespecs',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
