# Generated by Django 2.1.3 on 2019-02-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_views',
            field=models.IntegerField(default=0),
        ),
    ]
