# Generated by Django 2.1.3 on 2019-01-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='cover_images/'),
        ),
    ]
