# Generated by Django 2.1.3 on 2019-01-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0002_auto_20190116_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_image',
        ),
    ]
